version: "2"
services:
  db: 
    image: mysql:5.6 
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci #文字コードの設定
    environment:
      MYSQL_ROOT_PASSWORD: password 
      MYSQL_DATABASE: YOMEBA_ver_1_development 
    volumes:
      - mysql-data:/var/lib/mysql 
    ports:
      - "3306:3306" 

  app: 
    build: . 
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'" #railsの起動

    volumes:
      - .:/YOMEBA 
      - bundle:/usr/local/bundle 
    ports:
      - "3000:3000" 
    depends_on: 
      - db

volumes:
  mysql-data: 
  bundle: 