version: "2"
services:
  db: 
    image: mysql:5.6 
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci #文字コードの設定
    environment:
      MYSQL_ROOT_PASSWORD: password #データベースユーザ「root」のパスワード
      MYSQL_DATABASE: YOMEBA_ver_1_development #データベース名
    volumes:
      - mysql-data:/var/lib/mysql #名前付きボリュームでデータを永続化 ※ Dockerの管理下にデータを保管
    ports:
      - "3306:3306" #ポート設定

  app: #アプリ用コンテナの定義
    build: . #DockerFileを素にコンテナイメージを作成
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'" #railsの起動

    volumes:
      - .:/YOMEBA #ローカルのディレクトリをコンテナにマウント
      - bundle:/usr/local/bundle #bundle install後のbuildを不要にするため
    ports:
      - "3000:3000" #ポート設定
    depends_on: #作成順序の設定 「db」→「app」
      - db

volumes:
  mysql-data: #名前付きボリューム
  bundle: #bundle install後のbuildを不要にするため