CREATE_BOOK_VALIDATION_ERROR =  "タイトル、ジャンルは必須です。"
CREATE_GENRE_VALIDATION_ERROR = "ジャンルの内容は必須です。"
BOOK_INVALID_ERROR = "本が見つかりません。"
CREATE_GENRE_SUCCESS = "ジャンルが登録出来ました"
CREATE_BOOK_SUCCESS = "本の登録に成功しました"
BOOK_TRUSH_SUCCESS = "ゴミ箱への移動に成功しました"
BOOK_DESTROY_SUCCESS = "完全削除しました"