default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: db

development:
  <<: *default
  database: YOMEBA_ver_1_development

test:
  <<: *default
  database: YOMEBA_ver_1_test

production:
  <<: *default
  database: YOMEBA_ver_1_production
  username: YOMEBA_ver_1
  password: <%= ENV['YOMEBA_VER_1_DATABASE_PASSWORD'] %>
